name: CD

on:
  workflow_dispatch:
    inputs:

permissions:
  id-token: write
  contents: read

env:
  DOGU_AWS_REGION: ap-northeast-2

jobs:
  build-prod-dogu-docs:
    runs-on: build-dogu-docs

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - uses: actions/setup-go@v3
        with:
          go-version: '^1.18'

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1-node16
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.DOGU_AWS_REGION }}

      - name: Login to Amazon ECR Private
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          push: true
          context: .
          tags: ${{ steps.login-ecr.outputs.registry }}/prod-dogu-docs:latest
          platforms: linux/arm64
          target: dogu-docs

  release-prod-dogu-docs:
    runs-on: prod-dogu-docs
    needs: build-prod-dogu-docs

    steps:
      - name: Checkout
        uses: Bhacaz/checkout-files@v2
        with:
          files: docker-compose.yml

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1-node16
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.DOGU_AWS_REGION }}

      - name: Login to Amazon ECR Private
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Run
        run: |
          docker compose -f docker-compose.prod.yml rm -f
          docker compose -f docker-compose.prod.yml pull prod-dogu-docs
          docker compose -f docker-compose.prod.yml up -d prod-dogu-docs
          docker image prune -f

  send-slack:
    runs-on: build-dogu-docs
    needs: [release-prod-dogu-docs]

    steps:
      - name: Send Slack
        uses: dogu-team/slack@v1.0
        with:
          template: 'CD'
          slack-channel-id: 'C03PL9TC44Q'
          fail: failure()
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
