name: 🚀release-docs-gcp

on:
  workflow_dispatch:
    inputs:

permissions:
  id-token: write
  contents: read

env:
  DOGU_AWS_REGION: ap-northeast-2
  DOCS_GA_ID: G-5WLY043T9W
  DOGU_GCP_REGION: asia-northeast3
  DOGU_GCP_PROJECT_ID: ${{secrets.GCP_DEV_PROJECT_ID}}
  DOGU_DOCS_GAR_LOCATION: asia-northeast3-docker.pkg.dev/${{secrets.GCP_DEV_PROJECT_ID}}/dogu-docs-test

jobs:
  build:
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Cache Yarn Unplugged
        uses: actions/cache@v3
        id: cache_yarn_unplugged
        env:
          cache-name: cache-yarn-unplugged
        with:
          path: ${{ github.workspace }}/.yarn/unplugged
          key: ${{ runner.os }}-${{ env.cache-name }}-${{ hashFiles('yarn.lock') }}

      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: yarn

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Write env for production
        run: echo "GOOGLE_ANALYTICS_ID=$GOOGLE_ANALYTICS_ID" >> ./docs/.env
        env:
          GOOGLE_ANALYTICS_ID: ${{ env.DOCS_GA_ID }}

      - name: Build docs
        run: yarn build

      - id: auth
        name: Authenticate with Google Cloud
        uses: "google-github-actions/auth@v1"
        with:
          credentials_json: "${{ secrets.GCP_DEV_CICD_SA_KEY }}"

      - name: "Set up Cloud SDK"
        uses: "google-github-actions/setup-gcloud@v1"

      - name: Login to Artifact Registry
        uses: docker/login-action@v2
        with:
          registry: ${{env.DOGU_GCP_REGION}}-docker.pkg.dev
          username: oauth2accesstoken
          password: ${{ steps.auth.outputs.access_token }}
      
      # - name: "Docker auth"
      #   run: |-
      #     gcloud auth configure-docker ${{ env.DOGU_GCP_REGION }}-docker.pkg.dev --quiet
      
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: ${{env.DOGU_DOCS_GAR_LOCATION}}/dogu-docs-test:latest

  # release:
  #   runs-on: ubuntu-latest
  #   needs: build

  #   steps:
  #     - name: "Deploy image"
  #       run: |-
  #         gcloud run deploy dogu-docs-test \
  #           --image ${{ env.DOGU_DOCS_GAR_LOCATION }} \
  #           --platform managed \
  #           --region ${{ env.DOGU_GCP_REGION }} \
  #           --allow-unauthenticated \
  #           --project ${{ env.DOGU_GCP_PROJECT_ID }}


  # crawl-docs:
  #   runs-on: ubuntu-latest
  #   needs: release
  #   steps:
  #     - name: Algolia recrawl
  #       uses: algolia/algoliasearch-crawler-github-actions@v1.1.9
  #       id: algolia_crawler
  #       with:
  #         crawler-user-id: ${{ secrets.DOCS_CRAWLER_USER_ID }}
  #         crawler-api-key: ${{ secrets.DOCS_CRAWLER_API_KEY }}
  #         algolia-app-id: ${{ secrets.DOCS_ALGOLIA_APP_ID }}
  #         algolia-api-key: ${{ secrets.DOCS_ALGOLIA_API_KEY }}
  #         site-url: 'https://docs.dogutech.io'
  #         crawler-name: 'dogutech'

  # send-slack:
  #   runs-on: ubuntu-latest
  #   needs: crawl-docs
  #   if: ${{ always() }}

  #   steps:
  #     - name: Send Slack
  #       uses: dogu-team/slack@v1.0
  #       with:
  #         template: 'CD'
  #         slack-channel-id: 'C057ML9UH34'
  #         result-status: ${{ needs.crawl-docs.result }}
  #         ignore-notify: false
  #       env:
  #         SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
